/* ----------------1.报告列表--------------------------------- */

// 获取外部评估报告列表
export const GET_EXTERNAL_REPORT_LIST = 'GET_EXTERNAL_REPORT_LIST'
// loading
export const EXTERNAL_REPORT_LIST_LOADING = 'EXTERNAL_REPORT_LIST_LOADING'
// 获取外部评估报告列表成功
export const GET_EXTERNAL_REPORT_LIST_SUCCESS = 'GET_EXTERNAL_REPORT_LIST_SUCCESS'
// 获取外部评估报告列表失败
export const GET_EXTERNAL_REPORT_LIST_FAILED = 'GET_EXTERNAL_REPORT_LIST_FAILED'

// 获取内部评估报告列表
export const GET_INTERNAL_REPORT_LIST = 'GET_INTERNAL_REPORT_LIST'
// loading
export const INTERNAL_REPORT_LIST_LOADING = 'INTERNAL_REPORT_LIST_LOADING'
// 获取内部评估报告列表成功
export const GET_INTERNAL_REPORT_LIST_SUCCESS = 'GET_INTERNAL_REPORT_LIST_SUCCESS'
// 获取内部评估报告列表失败
export const GET_INTERNAL_REPORT_LIST_FAILED = 'GET_INTERNAL_REPORT_LIST_FAILED'

// 外部评估列表加载更多
export const GET_MORE_EXTERNAL_REPORT_LIST = 'GET_MORE_EXTERNAL_REPORT_LIST'
export const MORE_EXTERNAL_REPORT_LIST_LOADING = 'MORE_EXTERNAL_REPORT_LIST_LOADING'
export const GET_MORE_EXTERNAL_REPORT_LIST_SUCCESS = 'GET_MORE_EXTERNAL_REPORT_LIST_SUCCESS'
export const GET_MORE_EXTERNAL_REPORT_LIST_FAILED = 'GET_MORE_EXTERNAL_REPORT_LIST_FAILED'

// 内部评估列表加载更多
export const GET_MORE_INTERNAL_REPORT_LIST = 'GET_MORE_INTERNAL_REPORT_LIST'
export const MORE_INTERNAL_REPORT_LIST_LOADING = 'MORE_INTERNAL_REPORT_LIST_LOADING'
export const GET_MORE_INTERNAL_REPORT_LIST_SUCCESS = 'GET_MORE_INTERNAL_REPORT_LIST_SUCCESS'
export const GET_MORE_INTERNAL_REPORT_LIST_FAILED = 'GET_MORE_INTERNAL_REPORT_LIST_FAILED'
