// 提交个人信息数据
export const UPDATE_BASEINFO = 'UPDATE_BASEINFO'

export const BASEINFO_LOADING = 'BASEINFO_LOADING'

export const UPDATE_BASEINFO_SUCCESS = 'UPDATE_BASEINFO_SUCCESS'

export const UPDATE_BASEINFO_FAILED = 'UPDATE_BASEINFO_FAILED'

// 获取个人信息数据
export const GET_BASEINFO = 'GET_BASEINFO'

export const GET_BASEINFO_LOADING = 'GET_BASEINFO_LOADING'

export const GET_BASEINFO_SUCCESS = 'GET_BASEINFO_SUCCESS'

export const GET_BASEINFO_FAILED = 'GET_BASEINFO_FAILED'
