// 获取中医报告数据
export const GET_KUNGFU_DATA = 'GET_KUNGFU_DATA'

export const GET_KUNGFU_DATA_LOADING = 'GET_KUNGFU_DATA_LOADING'

export const GET_KUNGFU_DATA_SUCCESS = 'GET_KUNGFU_DATA_SUCCESS'

export const GET_KUNGFU_DATA_FAILED = 'GET_KUNGFU_DATA_FAILED'
