// 获取健康肖像数据
export const GET_HEALTHPORTRAIT_DATA = 'GET_HEALTHPORTRAIT_DATA'

export const GET_HEALTHPORTRAIT_DATA_LOADING = 'GET_HEALTHPORTRAIT_DATA_LOADING'

export const GET_HEALTHPORTRAIT_DATA_SUCCESS = 'GET_HEALTHPORTRAIT_DATA_SUCCESS'

export const GET_HEALTHPORTRAIT_DATA_FAILED = 'GET_HEALTHPORTRAIT_DATA_FAILED'
