
// 获取体检列表页面数据相关事件
export const GET_MEDICALRECORD_DATA = 'GET_MEDICALRECORD_DATA'

export const LOADING_MEDICALRECORD_DATA = 'LOADING_MEDICALRECORD_DATA'

export const GET_MEDICALRECORD_DATA_SUCCESS = 'GET_MEDICALRECORD_DATA_SUCCESS'

export const GET_MEDICALRECORD_DATA_FAILED = 'GET_MEDICALRECORD_DATA_FAILED'
