// 获取中医报告数据
export const GET_WESTERMEDICINE_DATA = 'GET_WESTERMEDICINE_DATA'

export const GET_WESTERMEDICINE_DATA_LOADING = 'GET_WESTERMEDICINE_DATA_LOADING'

export const GET_WESTERMEDICINE_DATA_SUCCESS = 'GET_WESTERMEDICINE_DATA_SUCCESS'

export const GET_WESTERMEDICINE_DATA_FAILED = 'GET_WESTERMEDICINE_DATA_FAILED'
