// 提交个病史状况
export const UPDATE_DISEASE = 'UPDATE_DISEASE'

export const DISEASE_LOADING = 'DISEASE_LOADING'

export const UPDATE_DISEASE_SUCCESS = 'UPDATE_DISEASE_SUCCESS'

export const UPDATE_DISEASE_FAILED = 'UPDATE_DISEASE_FAILED'

// 获取病史状况
export const GET_DISEASE = 'GET_DISEASE'

export const GET_DISEASE_LOADING = 'GET_DISEASE_LOADING'

export const GET_DISEASE_SUCCESS = 'GET_DISEASE_SUCCESS'

export const GET_DISEASE_FAILED = 'GET_DISEASE_FAILED'
