// 获取最近评估报告
export const GET_LATER_APPRAISAL_REPORT = 'GET_LATER_APPRAISAL_REPORT'
//  获取最近评估报告成功
export const GET_LATER_APPRAISAL_REPORT_SUCCESS = 'GET_LATER_APPRAISAL_REPORT_SUCCESS'
//  获取最近评估报告失败
export const GET_LATER_APPRAISAL_REPORT_FAILED = 'GET_LATER_APPRAISAL_REPORT_FAILED'


// 获取全部指标
export const GET_LATER_INDICATOR = 'GET_LATER_INDICATOR'
//  获取最近评估报告成功
export const GET_LATER_INDICATOR_SUCCESS = 'GET_LATER_INDICATOR_SUCCESS'
//  获取最近评估报告失败
export const GET_LATER_INDICATOR_FAILED = 'GET_LATER_INDICATOR_FAILED'


/**
 * 健康近况loading
 * @type {String}
 */
export const LOADING_HEALTH_CONDITION_ALL = 'LOADING_HEALTH_CONDITION_ALL'

export const GET_HEALTH_CONDITION_ALL = 'GET_HEALTH_CONDITION_ALL'

export const GET_HEALTH_CONDITION_ALL_SUCCESS = 'GET_HEALTH_CONDITION_ALL_SUCCESS'

export const GET_HEALTH_CONDITION_ALL_FAILED = 'GET_HEALTH_CONDITION_ALL_FAILED'
