/* ----------------1.加载用户信息--------------------------------- */

// 获取关注指标
export const GET_FOCUS_INDICATORS = 'GET_FOCUS_INDICATORS'

// loading
export const FOCUS_INDICATORS_LOADING = 'LOADING_LIFE_HISTOAR_LIST'

// 获取关注指标成功
export const GET_FOCUS_INDICATORS_SUCCESS = 'GET_FOCUS_INDICATORS_SUCCESS'

// 获取关注指标失败
export const GET_FOCUS_INDICATORS_FAILED = 'GET_FOCUS_INDICATORS_FAILED'


export const SUNMIT_FOCUS_INDICATORS_LOADING = 'SUNMIT_FOCUS_INDICATORS_LOADING'

// 提交关注指标
export const SUNMIT_FOCUS_INDICATORS = 'SUNMIT_FOCUS_INDICATORS'

// 提交关注指标成功
export const SUNMIT_FOCUS_INDICATORS_SUCCESS = 'SUNMIT_FOCUS_INDICATORS_SUCCESS'

// 提交关注指标失败
export const SUNMIT_FOCUS_INDICATORS_FAILED = 'SUNMIT_FOCUS_INDICATORS_FAILED'
