// 获取心养
export const GET_KEEPHEART_DATA = 'GET_KEEPHEART_DATA'

export const GET_KEEPHEART_DATA_LOADING = 'GET_KEEPHEART_DATA_LOADING'

export const GET_KEEPHEART_DATA_SUCCESS = 'GET_KEEPHEART_DATA_SUCCESS'

export const GET_KEEPHEART_DATA_FAILED = 'GET_KEEPHEART_DATA_FAILED'
