// 获取居养
export const GET_LIVEHEALTH_DATA = 'GET_LIVEHEALTH_DATA'

export const GET_LIVEHEALTH_DATA_LOADING = 'GET_LIVEHEALTH_DATA_LOADING'

export const GET_LIVEHEALTH_DATA_SUCCESS = 'GET_LIVEHEALTH_DATA_SUCCESS'

export const GET_LIVEHEALTH_DATA_FAILED = 'GET_LIVEHEALTH_DATA_FAILED'
