// 获取食养数据
export const GET_FOODHEALTH_DATA = 'GET_FOODHEALTH_DATA'

export const GET_FOODHEALTH_DATA_LOADING = 'GET_FOODHEALTH_DATA_LOADING'

export const GET_FOODHEALTH_DATA_SUCCESS = 'GET_FOODHEALTH_DATA_SUCCESS'

export const GET_FOODHEALTH_DATA_FAILED = 'GET_FOODHEALTH_DATA_FAILED'
