// 获取中医报告数据
export const GET_SPORTSHEALTH_DATA = 'GET_SPORTSHEALTH_DATA'

export const GET_SPORTSHEALTH_DATA_LOADING = 'GET_SPORTSHEALTH_DATA_LOADING'

export const GET_SPORTSHEALTH_DATA_SUCCESS = 'GET_SPORTSHEALTH_DATA_SUCCESS'

export const GET_SPORTSHEALTH_DATA_FAILED = 'GET_SPORTSHEALTH_DATA_FAILED'
