//   获取其他指标数据
export const GET_OTHERINDICATORSDETAILS_INFO = 'GET_OTHERINDICATORSDETAILS_INFO'
export const LOADING_OTHERINDICATORSDETAILS_INFO = 'LOADING_OTHERINDICATORSDETAILS_INFO'

//  获取数据成功
export const GET_OTHERINDICATORSDETAILS_INFO_SUCCESS = 'GET_OTHERINDICATORSDETAILS_INFO_SUCCESS'
//  获取数据失败
export const GET_OTHERINDICATORSDETAILS_INFO_FAILED = 'GET_OTHERINDICATORSDETAILS_INFO_FAILED'

