// 获取外部报告数据
export const GET_EXTERNALDETAILS_DATA = 'GET_EXTERNALDETAILS_DATA'

export const GET_EXTERNALDETAILS_DATA_LOADING = 'GET_EXTERNALDETAILS_DATA_LOADING'

export const GET_EXTERNALDETAILS_DATA_SUCCESS = 'GET_EXTERNALDETAILS_DATA_SUCCESS'

export const GET_EXTERNALDETAILS_DATA_FAILED = 'GET_EXTERNALDETAILS_DATA_FAILED'
