// 获取中医报告数据
export const GET_AFTERCARE_DATA = 'GET_AFTERCARE_DATA'

export const GET_AFTERCARE_DATA_LOADING = 'GET_AFTERCARE_DATA_LOADING'

export const GET_AFTERCARE_DATA_SUCCESS = 'GET_AFTERCARE_DATA_SUCCESS'

export const GET_AFTERCARE_DATA_FAILED = 'GET_AFTERCARE_DATA_FAILED'
