
// 获取血压 血脂柱状图数据
export const GET_PRESSURE_DATA = 'GET_PRESSURE_DATA'

export const LOADING_PRESSURE_DATA = 'LOADING_PRESSURE_DATA'

export const GET_PRESSURE_DATA_SUCCESS = 'GET_PRESSURE_DATA_SUCCESS'

export const GET_PRESSURE_DATA_FAILED = 'GET_PRESSURE_DATA_FAILED'
