// 获取中医报告数据
export const GET_CHINESEMEDICINE_DATA = 'GET_CHINESEMEDICINE_DATA'

export const GET_CHINESEMEDICINE_DATA_LOADING = 'GET_CHINESEMEDICINE_DATA_LOADING'

export const GET_CHINESEMEDICINE_DATA_SUCCESS = 'GET_CHINESEMEDICINE_DATA_SUCCESS'

export const GET_CHINESEMEDICINE_DATA_FAILED = 'GET_CHINESEMEDICINE_DATA_FAILED'
